replicaCount: 2
image:
  repository: "REPLACE_WITH_ECR_ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/taskforge-frontend"
  tag: "latest"
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  host: example.com
