apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mern-db-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: mern-db-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGO_URI
+      remoteRef:
+        key: /prod/mern/mongo_uri
+        property: uri
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${AWS_REGION}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
